data:
  external:
    {}

  nomis:
    years: [2019,2018,2017,2016]
    geography: TYPE459
    #2013 nuts 2, nuts 3, lep 2017
    #[TYPE450, TYPE449, TYPE459]

seed: 42

models:
  word2vec:
    size: 300
    window: 10
    min_count: 5
    iter: 20
